import { Inter } from "next/font/google";
import "./globals.css";

import UIProvider from "./provider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 max-w-6xl">
          <UIProvider>
            <Header />
            {children}
          </UIProvider>
        </div>
      </body>
    </html>
  );
}
